const API = 'http://127.0.0.1:48152'
const $ = (id) => document.getElementById(id)
let token = 'a080962698e6ba225c88dce4def5805f0edf0a9b4ab5603f'
let domain = ''
const request = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Bridge error'); return data }
const currentDomain = async () => { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); try { return new URL(tabs[0]?.url || '').hostname.replace(/^www\./, '') } catch { return '' } }
const render = async () => { domain = await currentDomain(); $('domain').textContent = domain || 'Current website'; try { await request('/health'); $('status').textContent = 'BRIDGE ONLINE'; $('status').classList.add('online'); const entries = await request('/get-credentials', { method: 'POST', body: JSON.stringify({ domain }) }); $('entries').innerHTML = ''; $('empty').classList.toggle('hidden', entries.length > 0); entries.forEach((entry) => { const row = document.createElement('div'); row.className = 'entry'; row.innerHTML = `<div class="entry-copy"><strong>${escapeHtml(entry.name)}</strong><small>${escapeHtml(entry.login || entry.domain)}</small></div><button data-id="${escapeHtml(entry.id)}">Fill</button>`; row.querySelector('button').addEventListener('click', () => fill(entry)); $('entries').appendChild(row) }) } catch (error) { $('status').textContent = 'BRIDGE OFFLINE'; $('status').classList.remove('online'); $('locked').classList.toggle('hidden', !String(error.message).includes('locked')); $('empty').classList.add('hidden') } }
const fill = async (entry) => { const tabs = await chrome.tabs.query({ active: true, currentWindow: true }); await chrome.tabs.sendMessage(tabs[0].id, { type: 'ENZO_FILL', credential: entry }); window.close() }
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]))
$('save-token').addEventListener('click', async () => { token = $('token').value.trim(); if (!token) return; await chrome.storage.local.set({ token }); $('setup').classList.add('hidden'); $('app').classList.remove('hidden'); await render() })
$('refresh').addEventListener('click', render)
$('generate').addEventListener('click', async () => { try { const result = await request('/generate', { method: 'POST', body: JSON.stringify({ length: 20 }) }); $('password').textContent = result.password; $('generated').classList.remove('hidden') } catch { $('generated').classList.add('hidden') } })
$('copy').addEventListener('click', () => navigator.clipboard.writeText($('password').textContent))
chrome.storage.local.get('token').then(async (result) => { token = result.token || ''; if (token) { $('setup').classList.add('hidden'); $('app').classList.remove('hidden'); await render() } else $('setup').classList.remove('hidden') })
