import { useEffect, useMemo, useState } from 'react'
import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import { ArrowRight, Check, ChevronDown, Copy, Eye, Fingerprint, KeyRound, LockKeyhole, Menu, Plus, RefreshCw, Search, Settings, ShieldCheck, Sparkles, UserRound, X } from 'lucide-react'

type View = 'vault' | 'generator' | 'settings'
type Category = 'all' | 'web' | 'apps' | 'notes'
type IncludeOptions = { upper: boolean; lower: boolean; numbers: boolean; symbols: boolean }
type Language = 'ru' | 'en'
type Entry = { id: string; name: string; domain: string; login: string; password: string; category: string; note: string }
type FormState = Omit<Entry, 'id'>
const blankForm: FormState = { name: '', domain: '', login: '', password: '', category: 'web', note: '' }
const categories: { id: Category; label: string }[] = [{ id: 'all', label: 'Все записи' }, { id: 'web', label: 'Веб-сайты' }, { id: 'apps', label: 'Приложения' }, { id: 'notes', label: 'Заметки' }]
const copyByLanguage = {
  ru: { vault: 'Ваши доступы', generator: 'Генератор', settings: 'Настройки', vaultLabel: 'Хранилище', generatorLabel: 'Генератор', settingsLabel: 'Настройки', add: 'Добавить запись', search: 'Поиск по хранилищу...', protected: 'ЗАЩИЩЕНО', strength: 'Надежность', generate: 'Сгенерировать новый', copied: 'Скопировано в буфер', empty: 'Хранилище пока пусто', emptyHint: 'Добавьте первую запись, чтобы сохранить доступ.', lang: 'Язык' },
  en: { vault: 'Your vault', generator: 'Generator', settings: 'Settings', vaultLabel: 'Vault', generatorLabel: 'Generator', settingsLabel: 'Settings', add: 'Add entry', search: 'Search your vault...', protected: 'PROTECTED', strength: 'Strength', generate: 'Generate new password', copied: 'Copied to clipboard', empty: 'Your vault is empty', emptyHint: 'Add your first entry to save an access.', lang: 'Language' },
}

function App() {
  const [screen, setScreen] = useState<'checking' | 'setup' | 'locked' | 'vault'>('checking')
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('enzo.language') as Language) || 'ru')
  const [pin, setPin] = useState('')
  const [entries, setEntries] = useState<Entry[]>([])
  const [view, setView] = useState<View>('vault')
  const [category, setCategory] = useState<Category>('all')
  const [query, setQuery] = useState('')
  const [copied, setCopied] = useState('')
  const [error, setError] = useState('')
  const [helloBusy, setHelloBusy] = useState(false)
  const [helloEnabled, setHelloEnabled] = useState(false)
  const [bridgeToken, setBridgeToken] = useState('')
  const [clipboardTimeout, setClipboardTimeout] = useState<number>(() => Number(localStorage.getItem('enzo.clipboardTimeout') ?? '15'))
  const [modal, setModal] = useState<'entry' | 'pin' | null>(null)
  const [editing, setEditing] = useState<Entry | null>(null)
  const [form, setForm] = useState<FormState>(blankForm)
  const [length, setLength] = useState(20)
  const [include, setInclude] = useState<IncludeOptions>({ upper: true, lower: true, numbers: true, symbols: true })
  const [generated, setGenerated] = useState('')
  const text = copyByLanguage[language]

  useEffect(() => { void (async () => { try { const exists = await invoke<boolean>('vault_exists'); setScreen(exists ? 'locked' : 'setup') } catch { setScreen('setup') } })(); const unlisten = listen('vault-lock', () => { setScreen('locked'); setEntries([]) }); return () => { unlisten.then((dispose) => dispose()) } }, [])
  useEffect(() => { if (screen === 'vault') void refreshEntries() }, [screen])
  useEffect(() => { if (screen === 'vault') void (async () => { try { setHelloEnabled(await invoke<boolean>('windows_hello_enabled')) } catch { setHelloEnabled(false) } })() }, [screen])
  useEffect(() => { if (screen === 'vault') void (async () => { try { setBridgeToken(await invoke<string>('bridge_token')) } catch { setBridgeToken('') } })() }, [screen])

  const refreshEntries = async () => { try { setEntries(await invoke<Entry[]>('list_entries')) } catch (e) { setError(String(e)) } }
  const copy = (value: string) => { navigator.clipboard?.writeText(value); setCopied(value); window.setTimeout(() => setCopied(''), 1600); if (clipboardTimeout > 0) window.setTimeout(() => { if (navigator.clipboard) void navigator.clipboard.writeText('') }, clipboardTimeout * 1000) }
  const unlock = async () => { setError(''); try { await invoke('unlock_vault', { pin }); setPin(''); setScreen('vault') } catch (e) { setError(String(e).replace('Error: ', '')) } }
  const unlockWithHello = async () => { setError(''); setHelloBusy(true); try { await invoke('unlock_with_windows_hello'); setPin(''); setScreen('vault') } catch (e) { setError(String(e).replace('Error: ', '')) } finally { setHelloBusy(false) } }
  const createVault = async () => { if (pin.length < 4) { setError('PIN должен содержать минимум 4 цифры'); return } try { await invoke('create_vault', { pin }); setPin(''); setScreen('vault') } catch (e) { setError(String(e)) } }
  const lock = async () => { try { await invoke('lock_vault'); setEntries([]) } catch { /* browser preview */ } setScreen('locked'); setPin('') }
  const close = () => { void invoke('hide_window').catch(() => undefined) }
  const openEntry = (entry?: Entry) => { setEditing(entry ?? null); setForm(entry ? { name: entry.name, domain: entry.domain, login: entry.login, password: entry.password, category: entry.category, note: entry.note } : blankForm); setModal('entry') }
  const saveEntry = async () => { if (!form.name.trim()) { setError('Укажите название записи'); return } const entry: Entry = { ...form, id: editing?.id ?? `${Date.now()}-${Math.random().toString(36).slice(2)}` }; try { await invoke(editing ? 'update_entry' : 'create_entry', { entry }); setModal(null); setError(''); await refreshEntries() } catch (e) { setError(String(e)) } }
  const removeEntry = async (id: string) => { if (!window.confirm('Удалить эту запись?')) return; await invoke('delete_entry', { id }); await refreshEntries() }
  const changePin = async () => { if (pin.length < 4) { setError('PIN должен содержать минимум 4 цифры'); return } try { await invoke('change_pin', { pin }); setPin(''); setModal(null); setError('PIN изменён') } catch (e) { setError(String(e)) } }
  const enableHello = async () => { try { await invoke('enable_windows_hello'); setHelloEnabled(true); setError('Windows Hello включён для этого устройства') } catch (e) { setError(String(e).replace('Error: ', '')) } }
  const generate = () => { const pools = [include.upper && 'ABCDEFGHJKLMNPQRSTUVWXYZ', include.lower && 'abcdefghijkmnopqrstuvwxyz', include.numbers && '23456789', include.symbols && '!@#$%^&*'].filter(Boolean) as string[]; const source = pools.join('') || 'abcdefghijklmnopqrstuvwxyz'; const bytes = new Uint32Array(length); crypto.getRandomValues(bytes); setGenerated(Array.from(bytes, (byte) => source[byte % source.length]).join('')) }
  const setTimeoutValue = (value: number) => { setClipboardTimeout(value); localStorage.setItem('enzo.clipboardTimeout', String(value)) }
  const entropyBits = generated ? Math.round(generated.length * Math.log2([include.upper && 'ABCDEFGHJKLMNPQRSTUVWXYZ', include.lower && 'abcdefghijkmnopqrstuvwxyz', include.numbers && '23456789', include.symbols && '!@#$%^&*'].filter(Boolean).join('').length || 26)) : 0
  const strength = !generated ? { label: language === 'ru' ? 'НЕ СОЗДАН' : 'NOT GENERATED', tone: 'empty', bars: 0 } : entropyBits >= 100 ? { label: language === 'ru' ? 'ОЧЕНЬ СИЛЬНЫЙ' : 'VERY STRONG', tone: 'very-strong', bars: 5 } : entropyBits >= 75 ? { label: language === 'ru' ? 'СИЛЬНЫЙ' : 'STRONG', tone: 'strong', bars: 4 } : entropyBits >= 50 ? { label: language === 'ru' ? 'СРЕДНИЙ' : 'MEDIUM', tone: 'medium', bars: 3 } : entropyBits >= 30 ? { label: language === 'ru' ? 'СЛАБЫЙ' : 'WEAK', tone: 'weak', bars: 2 } : { label: language === 'ru' ? 'ОЧЕНЬ СЛАБЫЙ' : 'VERY WEAK', tone: 'very-weak', bars: 1 }
  const filtered = useMemo(() => entries.filter((entry) => (category === 'all' || entry.category === category) && `${entry.name} ${entry.domain} ${entry.login}`.toLowerCase().includes(query.toLowerCase())), [entries, category, query])

  if (screen === 'checking') return <main className="loading-screen"><span className="brand-mark">E</span></main>
  if (screen === 'setup') return <SetupScreen pin={pin} setPin={setPin} create={createVault} error={error} close={close} />
  if (screen === 'locked') return <LockScreen pin={pin} setPin={setPin} unlock={unlock} unlockWithHello={unlockWithHello} helloBusy={helloBusy} error={error} close={close} />
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">E</span><span>enzo</span><span className="status-dot" /></div><div className="top-actions"><div className="app-language" aria-label={text.lang}><button className={language === 'ru' ? 'active' : ''} onClick={() => { setLanguage('ru'); localStorage.setItem('enzo.language', 'ru') }}>RU</button><span>/</span><button className={language === 'en' ? 'active' : ''} onClick={() => { setLanguage('en'); localStorage.setItem('enzo.language', 'en') }}>EN</button></div><button className="icon-button" onClick={lock} aria-label="Заблокировать"><LockKeyhole size={16} /></button><button className="icon-button close-button" onClick={close} aria-label="Скрыть в трей"><X size={16} /></button></div></header>
    <section className="content"><div className="welcome-row"><div><p className="eyebrow">VAULT / {String(entries.length).padStart(2, '0')} ENTRIES</p><h1>{view === 'vault' ? text.vault : view === 'generator' ? text.generator : text.settings}</h1></div><div className="secure-badge"><ShieldCheck size={14} /> {text.protected}</div></div>
      {view === 'vault' && <><div className="search-box"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={text.search} /><span className="shortcut">⌘ K</span></div><div className="category-tabs">{categories.map((item) => <button className={category === item.id ? 'active' : ''} onClick={() => setCategory(item.id)} key={item.id}>{language === 'en' ? ({ all: 'All items', web: 'Websites', apps: 'Apps', notes: 'Notes' }[item.id]) : item.label}</button>)}</div><div className="entry-list">{filtered.map((entry) => <article className="entry" key={entry.id} onClick={() => openEntry(entry)}><div className="service-logo" style={{ color: '#ff4668', borderColor: '#ff003330' }}>{entry.name.slice(0, 2).toUpperCase()}</div><div className="entry-info"><strong>{entry.name}</strong><span>{entry.login || entry.domain || (language === 'en' ? 'No login' : 'Без логина')}</span></div><button className="copy-button" onClick={(e) => { e.stopPropagation(); copy(entry.password) }} aria-label="Скопировать пароль"><Copy size={15} /></button><button className="entry-arrow" aria-label="Открыть запись"><ArrowRight size={16} /></button></article>)}</div>{filtered.length === 0 && <div className="empty-state"><KeyRound size={25} /><strong>{text.empty}</strong><span>{text.emptyHint}</span></div>}<button className="add-entry" onClick={() => openEntry()}><Plus size={16} /> {text.add}<kbd>⌘ N</kbd></button></>}
      {view === 'generator' && <Generator language={language} generated={generated} length={length} setLength={setLength} include={include} setInclude={setInclude} generate={generate} copy={copy} strength={strength} />}
      {view === 'settings' && <SettingsPanel language={language} lock={lock} openPin={() => { setPin(''); setModal('pin') }} enableHello={enableHello} helloEnabled={helloEnabled} clipboardTimeout={clipboardTimeout} setClipboardTimeout={setTimeoutValue} bridgeToken={bridgeToken} />}
    </section>{copied && <div className="toast"><Check size={15} /> {text.copied}</div>}<nav className="bottom-nav"><button className={view === 'vault' ? 'active' : ''} onClick={() => setView('vault')}><KeyRound size={17} /><span>{text.vaultLabel}</span></button><button className={view === 'generator' ? 'active' : ''} onClick={() => setView('generator')}><Sparkles size={17} /><span>{text.generatorLabel}</span></button><button className={view === 'settings' ? 'active' : ''} onClick={() => setView('settings')}><Settings size={17} /><span>{text.settingsLabel}</span></button></nav>
    {modal === 'entry' && <EntryModal form={form} setForm={setForm} save={saveEntry} remove={editing ? () => { void removeEntry(editing.id); setModal(null) } : undefined} close={() => setModal(null)} editing={Boolean(editing)} />}{modal === 'pin' && <PinModal pin={pin} setPin={setPin} save={changePin} close={() => setModal(null)} error={error} />}
  </main>
}

function SetupScreen({ pin, setPin, create, error, close }: { pin: string; setPin: (v: string) => void; create: () => void; error: string; close: () => void }) { return <main className="lock-screen setup-screen"><div className="lock-top"><div className="brand"><span className="brand-mark">E</span><span>enzo</span></div><button className="icon-button" onClick={close}><X size={16} /></button></div><div className="lock-content"><div className="fingerprint-wrap"><KeyRound size={48} strokeWidth={1.25} /></div><p className="eyebrow">FIRST RUN</p><h1>Создайте хранилище</h1><p className="lock-copy">Придумайте PIN-код. Он будет использоваться для шифрования всех ваших данных.</p><PinInput pin={pin} setPin={setPin} /><button className="hello-button" onClick={create}><ShieldCheck size={18} /> Создать защищённое хранилище</button>{error && <p className="form-error">{error}</p>}<p className="security-note"><ShieldCheck size={13} /> AES-256-GCM + Argon2id</p></div><div className="lock-footer">Данные останутся только на этом устройстве</div></main> }
function LockScreen({ pin, setPin, unlock, unlockWithHello, helloBusy, error, close }: { pin: string; setPin: (v: string) => void; unlock: () => void; unlockWithHello: () => void; helloBusy: boolean; error: string; close: () => void }) { return <main className="lock-screen"><div className="lock-top"><div className="brand"><span className="brand-mark">E</span><span>enzo</span></div><button className="icon-button" onClick={close}><X size={16} /></button></div><div className="lock-content"><div className="fingerprint-wrap"><Fingerprint size={54} strokeWidth={1.25} /><span className="pulse-ring" /></div><p className="eyebrow">PRIVATE ACCESS</p><h1>Хранилище заблокировано</h1><p className="lock-copy">Подтвердите личность через Windows Hello или введите PIN-код.</p><PinInput pin={pin} setPin={setPin} onEnter={unlock} /> <button className="hello-button" onClick={unlockWithHello} disabled={helloBusy}><Fingerprint size={18} /> {helloBusy ? 'Ожидание подтверждения...' : 'Войти через Windows Hello'}</button>{error && <p className="form-error">{error}</p>}<button className="pin-link" onClick={unlock}>Открыть по PIN-коду <ChevronDown size={14} /></button></div><div className="lock-footer"><ShieldCheck size={13} /> Ключ очищается после блокировки</div></main> }
function PinInput({ pin, setPin, onEnter }: { pin: string; setPin: (v: string) => void; onEnter?: () => void }) { return <div className="pin-entry"><label htmlFor="pin-code">PIN-код</label><input id="pin-code" autoFocus type="password" inputMode="numeric" maxLength={6} value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, ''))} onKeyDown={(e) => e.key === 'Enter' && onEnter?.()} placeholder="Введите 4–6 цифр" aria-label="PIN-код" /><div className="pin-dots">{[0, 1, 2, 3, 4, 5].map((index) => <span className={index < pin.length ? 'filled' : ''} key={index} />)}</div></div> }

function Generator({ language, generated, length, setLength, include, setInclude, generate, copy, strength }: { language: Language; generated: string; length: number; setLength: (v: number) => void; include: IncludeOptions; setInclude: (v: IncludeOptions) => void; generate: () => void; copy: (v: string) => void; strength: { label: string; tone: string; bars: number } }) { const options = language === 'en' ? [['upper', 'Uppercase', 'A-Z'], ['lower', 'Lowercase', 'a-z'], ['numbers', 'Numbers', '0-9'], ['symbols', 'Symbols', '!@#']] as const : [['upper', 'Заглавные буквы', 'A-Z'], ['lower', 'Строчные буквы', 'a-z'], ['numbers', 'Цифры', '0-9'], ['symbols', 'Спецсимволы', '!@#']] as const; return <div className="generator"><div className="password-output"><span>{generated || (language === 'en' ? 'Generate a password' : 'Нажмите генерацию')}</span><button onClick={() => generated && copy(generated)} aria-label="Скопировать"><Copy size={17} /></button></div><div className="strength"><div className="strength-label"><span>{language === 'en' ? 'Strength' : 'Надежность'}</span><b className={strength.tone}>{strength.label}</b></div><div className="strength-bar">{[0, 1, 2, 3, 4].map((bar) => <i className={bar < strength.bars ? strength.tone : ''} key={bar} />)}</div></div><div className="control-block"><div className="control-label"><span>{language === 'en' ? 'Password length' : 'Длина пароля'}</span><b>{length}</b></div><input type="range" min="8" max="64" value={length} onChange={(e) => setLength(Number(e.target.value))} /></div><div className="toggle-list">{options.map(([id, label, sample]) => <label className="toggle-row" key={id}><span><b>{sample}</b>{label}</span><input type="checkbox" checked={include[id]} onChange={() => setInclude({ ...include, [id]: !include[id] })} /><i /></label>)}</div><button className="primary-action" onClick={generate}><RefreshCw size={17} /> {language === 'en' ? 'Generate new password' : 'Сгенерировать новый'}</button></div> }
function SettingsPanel({ language, lock, openPin, enableHello, helloEnabled, clipboardTimeout, setClipboardTimeout, bridgeToken }: { language: Language; lock: () => void; openPin: () => void; enableHello: () => void; helloEnabled: boolean; clipboardTimeout: number; setClipboardTimeout: (v: number) => void; bridgeToken: string }) { const en = language === 'en'; return <div className="settings-list"><button className="setting-row setting-button" onClick={openPin}><div className="setting-icon"><LockKeyhole size={17} /></div><div><strong>{en ? 'Change PIN' : 'Изменить PIN-код'}</strong><span>{en ? 'Update encryption key' : 'Обновить ключ шифрования'}</span></div><ChevronDown size={15} className="setting-chevron" /></button><button className="setting-row setting-button" onClick={enableHello}><div className="setting-icon"><Fingerprint size={17} /></div><div><strong>Windows Hello</strong><span>{helloEnabled ? (en ? 'Active on this device' : 'Активен на этом устройстве') : (en ? 'Click to register this device' : 'Нажмите для регистрации этого устройства')}</span></div><span className={`toggle ${helloEnabled ? 'on' : ''}`}><i /></span></button><label className="setting-row setting-control"><div className="setting-icon"><Eye size={17} /></div><div><strong>{en ? 'Clipboard cleanup' : 'Очистка буфера'}</strong><span>{clipboardTimeout === 0 ? (en ? 'Never clean automatically' : 'Не очищать автоматически') : (en ? `After ${clipboardTimeout} seconds` : `Через ${clipboardTimeout} секунд`)}</span></div><select value={clipboardTimeout} onChange={(e) => setClipboardTimeout(Number(e.target.value))}><option value="5">5 sec</option><option value="15">15 sec</option><option value="30">30 sec</option><option value="0">{en ? 'Never' : 'Никогда'}</option></select></label><div className="setting-row"><div className="setting-icon"><UserRound size={17} /></div><div><strong>{en ? 'Local bridge' : 'Локальный мост'}</strong><span>127.0.0.1:48152 · {bridgeToken ? (en ? 'token ready' : 'токен готов') : (en ? 'off' : 'выключен')}</span></div><ChevronDown size={15} className="setting-chevron" /></div>{bridgeToken && <div className="bridge-token"><span>{en ? 'Extension token' : 'Токен расширения'}</span><code>{bridgeToken}</code><button onClick={() => navigator.clipboard?.writeText(bridgeToken)}><Copy size={13} /></button></div>}<div className="settings-divider" /><button className="settings-action" onClick={lock}><LockKeyhole size={16} /> {en ? 'Lock now' : 'Заблокировать сейчас'}</button></div> }

function EntryModal({ form, setForm, save, remove, close, editing }: { form: FormState; setForm: (v: FormState) => void; save: () => void; remove?: () => void; close: () => void; editing: boolean }) { const update = (key: keyof FormState, value: string) => setForm({ ...form, [key]: value }); return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">{editing ? 'EDIT ENTRY' : 'NEW ENTRY'}</p><h2>{editing ? 'Изменить запись' : 'Новая запись'}</h2></div><button className="icon-button" onClick={close}><X size={17} /></button></div><label>Название<input autoFocus value={form.name} onChange={(e) => update('name', e.target.value)} placeholder="Например, GitHub" /></label><label>Сайт или приложение<input value={form.domain} onChange={(e) => update('domain', e.target.value)} placeholder="github.com" /></label><label>Логин<input value={form.login} onChange={(e) => update('login', e.target.value)} /></label><label>Пароль<input type="password" value={form.password} onChange={(e) => update('password', e.target.value)} /></label><label>Категория<select value={form.category} onChange={(e) => update('category', e.target.value)}><option value="web">Веб-сайт</option><option value="apps">Приложение</option><option value="notes">Заметка</option></select></label><div className="modal-actions">{remove && <button className="danger-action" onClick={remove}>Удалить</button>}<button className="primary-action" onClick={save}><Check size={16} /> Сохранить</button></div></div></div> }
function PinModal({ pin, setPin, save, close, error }: { pin: string; setPin: (v: string) => void; save: () => void; close: () => void; error: string }) { return <div className="modal-backdrop"><div className="modal small-modal"><div className="modal-head"><div><p className="eyebrow">SECURITY</p><h2>Новый PIN-код</h2></div><button className="icon-button" onClick={close}><X size={17} /></button></div><p className="modal-copy">После изменения старый PIN перестанет работать.</p><input className="modal-pin" autoFocus type="password" inputMode="numeric" maxLength={6} value={pin} onChange={(e) => setPin(e.target.value.replace(/\D/g, ''))} placeholder="Введите новый PIN" /><button className="primary-action" onClick={save}>Сохранить новый PIN</button>{error && <p className="form-error">{error}</p>}</div></div> }
export default App
